In [0]:
import torch 
import numpy as np
import matplotlib.pyplot as plot

In [2]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,3)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
print(torch.cuda.device_count())

1


In [4]:
print(torch.cuda.get_device_name())

Tesla P100-PCIE-16GB


In [0]:
cuda0 = torch.device('cuda:0')

In [9]:
%%time
for i in range(10):
  a= np.random.rand(10000,10000)
  b= np.random.rand(10000,10000)
  np.add(a,b)



CPU times: user 21.3 s, sys: 125 ms, total: 21.4 s
Wall time: 21.5 s


In [14]:
%%time
for i in range(10):
  a_cpu= torch.randn(10000,10000)
  b_cpu= torch.randn(10000,10000)
  a_cpu.add_(b_cpu)

CPU times: user 17 s, sys: 35.7 ms, total: 17 s
Wall time: 17 s


In [15]:
%%time
for i in range(10):
  a= torch.randn(10000,10000,device = cuda0)
  b= torch.randn(10000,10000,device = cuda0)
  a.add_(b)

CPU times: user 1.26 ms, sys: 984 µs, total: 2.24 ms
Wall time: 2.85 ms


In [0]:
#auti grad

x=torch.ones([3,2],requires_grad=True)

In [17]:
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [18]:
y = x+5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [19]:
z=y*y+1
print(z)


tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [20]:
t= torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [0]:
t.backward()

In [22]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])
